<?xml version="1.0"?>
<robot>

	<!-- Wheel - Start -->
	<macro name="wheel" params="lr y">
		<link name="${lr}_wheel">
		  <collision>
		    <origin xyz="0 0 0" rpy="0 1.5708 1.5708" />
		    <geometry>
		     <cylinder length="${wheelThickness}" radius="${wheelRadius}"/>
		    </geometry>
			</collision>

			<visual>
			  <origin xyz="0 0 0" rpy="0 1.5708 1.5708" />
			  <geometry>
			   <cylinder length="${wheelThickness}" radius="${wheelRadius}"/>
			  </geometry>
			  <material name="black"/>
			</visual>

			<inertial>
			  <origin xyz="0 0 0" rpy="0 1.5708 1.5708" />
			  <mass value="0.2"/>
			  <cylinder_inertia m="0.2" r="${wheelRadius}" h="${wheelThickness}"/>
				<inertia ixx="0.4" ixy="0.1" ixz="0.1" iyy="0.4" iyz="0.1" izz="0.2"/>
			</inertial>
	 	</link>

	 	<joint name="${lr}_wheel_hinge" type="continuous">
		  <parent link="chassis"/>
		  <child link="${lr}_wheel"/>
		  <origin xyz="${chassisLength/4} ${y*(((wheelThickness+chassisWidth)/2)+.01)} ${wheelRadius}" rpy="0 0 0" /> 
		  <axis xyz="0 1 0" rpy="0 0 0" />
		  <!--<limit effort="100" velocity="100"/>-->
		  <!--<joint_properties damping="0.0" friction="0"/>-->
		  <dynamics damping="0.0" />
		</joint>

		<gazebo reference="${lr}_wheel">
			<mu1 value="1.0"/>
			<mu2 value="1.0"/>
			<kp  value="10000000.0" />
			<kd  value="1.0" />
			<fdir1 value="0 1 0"/>
			<material>Gazebo/Blue</material>
		</gazebo>

		<gazebo reference="${lr}_wheel_hinge">
			<implicitSpringDamper value='true' />
		</gazebo>

		<transmission name="${lr}_trans">
		  <type>transmission_interface/SimpleTransmission</type>
		  <joint name="${lr}_wheel_hinge">
		      <hardwareInterface>EffortJointInterface</hardwareInterface>
		  </joint>
		  <actuator name="${lr}Motor">
		  <hardwareInterface>hardwareInterface/EffortJointInterface</hardwareInterface>
		  <mechanicalReduction>10</mechanicalReduction>
		  </actuator>
		</transmission>
	</macro> 
	<!-- Wheel - End --> 

	<macro name="cylinder_inertia" params="m r h">
		<inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
		          iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
		          izz="${m*r*r/2}" /> 
	</macro>

	<macro name="box_inertia" params="m x y z">
		<inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
		          iyy="${m*(x*x+z*z)/12}" iyz = "0"
		          izz="${m*(x*x+z*z)/12}" /> 
	</macro>

	<macro name="sphere_inertia" params="m r">
		<inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
		          iyy="${2*m*r*r/5}" iyz = "0"
		          izz="${2*m*r*r/5}" /> 
	</macro>

</robot>
